services:
  swbot_connector_app:
    container_name: swbot_connector_app
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - SWITCHBOT_TOKEN=${SWITCHBOT_TOKEN}
      - SWITCHBOT_SECRET=${SWITCHBOT_SECRET}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - NODE_ENV=${APP_NODE_ENV:-production}
      - PORT=${APP_PORT:-3000}
    depends_on:
        - postgres
        - redis
    networks:
      - swbot_connector
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - swbot_connector
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - swbot_connector
    command: redis-server --save 60 1 --appendonly yes
#  ngrok:
#    image: ngrok/ngrok:latest
#    container_name: swbot_ngrok
#    restart: unless-stopped
#    environment:
#      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
#    command: http swbot_connector_app:3000
#    depends_on:
#      - swbot_connector_app
#    # Pour acc√©der au dashboard web (utile pour debugger)
#    ports:
#      - "4040:4040"
#    networks:
#        - swbot_connector
volumes:
  db-data:
    driver: local
networks:
    swbot_connector:
        driver: bridge